development:
  host: localhost
  adapter: sqlite3
  encoding: unicode
  database: ubuntufeed_development
  pool: 5

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ubuntufeed_test
  pool: 5
  username: postgres
  password: 123

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ubuntufeed_production
  pool: 5
  username: postgres
  password: 123
